"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ClipboardCheck, Download, MapPinned, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

type Product = { id: string; code: string; description: string; brand: string; supplier: string; cost?: number | null; ncm?: string };
type Movement = { id: string; date: string; sector: string; productCode: string; productDescription: string; reference: string; quantity: number; situation: "Cadastrado" | "Não cadastrado" | "Dúvida"; action: string; status: "Concluído" | "Pendente" | "Conferir"; notes: string; cost: number };
type Sector = { id: string; name: string; location: string; owner: string; start: string; end: string; status: "Não iniciado" | "Em andamento" | "Concluído" | "Pausado"; notes: string };
type Daily = { id: string; date: string; employees: number; counted: number; launched: number; registrations: number; pending: number; checks: number; notes: string };
type Tab = "overview" | "movements" | "sectors" | "daily";

const initialSectors: Sector[] = [
  { id: "loja", name: "Loja / Salão", location: "Área de vendas", owner: "", start: "", end: "", status: "Não iniciado", notes: "" },
  { id: "deposito", name: "Depósito", location: "Estoque interno", owner: "", start: "", end: "", status: "Não iniciado", notes: "" },
  { id: "externo", name: "Área externa", location: "Pátio", owner: "", start: "", end: "", status: "Não iniciado", notes: "" },
];
const today = () => new Date().toISOString().slice(0, 10);
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const number = (value: number) => value.toLocaleString("pt-BR");
const dateLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";
const load = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const save = (key: string, value: unknown) => localStorage.setItem(key, JSON.stringify(value));
const download = (filename: string, content: string, type = "text/csv;charset=utf-8") => { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); };
const csv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export function BalanceModule({ products, organizationId, userId }: { products: Product[]; organizationId: string | null; userId: string }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [movements, setMovements] = useState<Movement[]>(() => typeof window === "undefined" ? [] : load("central-balance-movements", []));
  const [sectors, setSectors] = useState<Sector[]>(() => typeof window === "undefined" ? initialSectors : load("central-balance-sectors", initialSectors));
  const [daily, setDaily] = useState<Daily[]>(() => typeof window === "undefined" ? [] : load("central-balance-daily", []));
  const [movementOpen, setMovementOpen] = useState(false); const [sectorOpen, setSectorOpen] = useState(false); const [dailyOpen, setDailyOpen] = useState(false);
  const counted = movements.reduce((sum, item) => sum + item.quantity, 0); const completed = movements.filter((item) => item.status === "Concluído").length;
  const tabs: Array<{ id: Tab; label: string }> = [{ id: "overview", label: "Visão geral" }, { id: "movements", label: "Contagens" }, { id: "sectors", label: "Setores" }, { id: "daily", label: "Produtividade" }];
  useEffect(() => { if (!organizationId) return; void (async()=>{
    const [sectorResult,countResult,dailyResult] = await Promise.all([
      supabase.from("inventory_sectors").select("*").eq("organization_id",organizationId).order("created_at"),
      supabase.from("inventory_counts").select("*,products(code,description)").eq("organization_id",organizationId).order("created_at",{ascending:false}),
      supabase.from("daily_productivity").select("*").eq("organization_id",organizationId).order("record_date",{ascending:false}),
    ]);
    if(sectorResult.error||countResult.error||dailyResult.error){toast.error("Parte do balanço não pôde ser sincronizada.");return;}
    const sectorData=sectorResult.data;const countData=countResult.data;const dailyData=dailyResult.data;
    if(sectorData?.length){const mapped=sectorData.map((x)=>({id:x.id,name:x.name,location:x.location,owner:x.owner_name,start:x.start_date||"",end:x.end_date||"",status:x.status,notes:x.notes})) as Sector[];setSectors(mapped);save("central-balance-sectors",mapped);}
    if(countData){const mapped=countData.map((x)=>({id:x.id,date:x.count_date,sector:sectorData?.find((s)=>s.id===x.sector_id)?.name||"",productCode:(x.products as {code?:string}|null)?.code||"",productDescription:(x.products as {description?:string}|null)?.description||"Produto",reference:x.physical_reference,quantity:Number(x.physical_quantity),situation:x.system_situation,action:x.action_taken,status:x.status,notes:x.notes,cost:Number(x.unit_cost)||0})) as Movement[];setMovements(mapped);save("central-balance-movements",mapped);}
    if(dailyData){const mapped=dailyData.map((x)=>({id:x.id,date:x.record_date,employees:x.employees,counted:x.counted,launched:x.launched,registrations:x.registrations,pending:x.pending,checks:x.checks,notes:x.notes})) as Daily[];setDaily(mapped);save("central-balance-daily",mapped);}
  })(); },[organizationId]);
  const updateMovements = async (value: Movement[]) => { const removed=movements.find((x)=>!value.some((v)=>v.id===x.id)); if(removed&&organizationId){const {error}=await supabase.from("inventory_counts").delete().eq("id",removed.id).eq("organization_id",organizationId);if(error)return void toast.error("Não foi possível excluir a contagem.");} setMovements(value);save("central-balance-movements", value);toast.success("Contagem excluída."); };
  const updateSectors = async (value: Sector[]) => { const removed=sectors.find((x)=>!value.some((v)=>v.id===x.id)); if(removed&&organizationId){const {error}=await supabase.from("inventory_sectors").delete().eq("id",removed.id).eq("organization_id",organizationId);if(error)return void toast.error("O setor possui contagens ou não pôde ser excluído.");} setSectors(value);save("central-balance-sectors", value);toast.success("Setor excluído."); };
  const updateDaily = async (value: Daily[]) => { const removed=daily.find((x)=>!value.some((v)=>v.id===x.id)); if(removed&&organizationId){const {error}=await supabase.from("daily_productivity").delete().eq("id",removed.id).eq("organization_id",organizationId);if(error)return void toast.error("Não foi possível excluir a jornada.");} setDaily(value);save("central-balance-daily", value);toast.success("Jornada excluída."); };
  async function addMovement(item: Movement) { if(organizationId){const product=products.find((p)=>p.code===item.productCode&&p.description===item.productDescription);const sectorRow=sectors.find((s)=>s.name===item.sector);if(!product){toast.error("Produto não encontrado no catálogo sincronizado.");return false;}const {error}=await supabase.from("inventory_counts").insert({id:item.id,organization_id:organizationId,product_id:product.id,sector_id:sectorRow?.id||null,count_date:item.date,physical_reference:item.reference,physical_quantity:item.quantity,system_situation:item.situation,action_taken:item.action,status:item.status,notes:item.notes,unit_cost:item.cost,created_by:userId});if(error){toast.error("Não foi possível sincronizar a contagem.");return false;}} const value=[item,...movements];setMovements(value);save("central-balance-movements",value);toast.success("Contagem registrada.");return true; }
  async function addSector(item: Sector) { if(organizationId){const {error}=await supabase.from("inventory_sectors").insert({id:item.id,organization_id:organizationId,name:item.name,location:item.location,owner_name:item.owner,start_date:item.start||null,end_date:item.end||null,status:item.status,notes:item.notes});if(error){toast.error("Não foi possível sincronizar o setor.");return false;}}const value=[item,...sectors];setSectors(value);save("central-balance-sectors",value);toast.success("Setor criado.");return true; }
  async function addDaily(item: Daily) { if(organizationId){const {data,error}=await supabase.from("daily_productivity").upsert({id:item.id,organization_id:organizationId,record_date:item.date,employees:item.employees,counted:item.counted,launched:item.launched,registrations:item.registrations,pending:item.pending,checks:item.checks,notes:item.notes,created_by:userId},{onConflict:"organization_id,record_date"}).select("id").single();if(error){toast.error("Não foi possível sincronizar a produtividade.");return false;}item.id=data.id;}const value=[item,...daily.filter((x)=>x.date!==item.date)];setDaily(value);save("central-balance-daily",value);toast.success("Produtividade salva.");return true; }
  function backup() { download(`backup-balanco-${today()}.json`, JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), movements, sectors, daily }, null, 2), "application/json"); toast.success("Backup do balanço baixado."); }
  return <section className="content balance-module">
    <div className="page-heading"><div><span className="eyebrow">ESTOQUE</span><h1>Balanço de estoque</h1><p>Contagem física, divergências, setores e produtividade usando o catálogo mestre.</p></div><div className="heading-actions"><Button variant="outline" onClick={backup}><Download size={17}/> Backup</Button><Button onClick={() => setMovementOpen(true)}><Plus size={17}/> Nova contagem</Button></div></div>
    <div className="balance-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}{item.id === "movements" && <span>{movements.length}</span>}</button>)}</div>
    {tab === "overview" && <><div className="metric-grid"><Metric label="Produtos na base" value={number(products.length)} hint="Catálogo unificado"/><Metric label="Lançamentos" value={number(movements.length)} hint={`${completed} concluídos`}/><Metric label="Quantidade contada" value={number(counted)} hint="Soma das contagens físicas"/><Metric label="Setores concluídos" value={`${sectors.filter((s) => s.status === "Concluído").length}/${sectors.length}`} hint="Andamento geral"/></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><h2>Andamento por setor</h2><span>{sectors.length} áreas</span></div>{sectors.map((sector) => <div className="balance-sector-line" key={sector.id}><div><strong>{sector.name}</strong><span>{sector.owner || "Responsável não definido"}</span></div><Badge variant={sector.status === "Concluído" ? "default" : "secondary"}>{sector.status}</Badge></div>)}</div><div className="panel"><div className="panel-heading"><h2>Últimas contagens</h2><span>{movements.length} registros</span></div>{movements.length ? movements.slice(0, 7).map((item) => <div className="recent-order" key={item.id}><div><strong>{item.productDescription}</strong><span>{item.sector || "Sem setor"} · {dateLabel(item.date)}</span></div><Badge variant="secondary">{item.status}</Badge><b>{number(item.quantity)}</b></div>) : <BalanceEmpty text="Nenhuma contagem registrada."/>}</div></div></>}
    {tab === "movements" && <Movements rows={movements} onNew={() => setMovementOpen(true)} onChange={updateMovements}/>} 
    {tab === "sectors" && <Sectors rows={sectors} onNew={() => setSectorOpen(true)} onChange={updateSectors}/>} 
    {tab === "daily" && <DailyView rows={daily} productsTotal={products.length} onNew={() => setDailyOpen(true)} onChange={updateDaily}/>} 
    <MovementDialog open={movementOpen} onOpenChange={setMovementOpen} products={products} sectors={sectors} onSave={addMovement}/>
    <SectorDialog open={sectorOpen} onOpenChange={setSectorOpen} onSave={addSector}/>
    <DailyDialog open={dailyOpen} onOpenChange={setDailyOpen} onSave={addDaily}/>
  </section>;
}

function Metric({ label, value, hint }: { label: string; value: string; hint: string }) { return <div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>; }
function BalanceEmpty({ text }: { text: string }) { return <div className="empty-panel"><ClipboardCheck/><strong>{text}</strong><span>Use o botão de novo lançamento para começar.</span></div>; }

function Movements({ rows, onNew, onChange }: { rows: Movement[]; onNew: () => void; onChange: (rows: Movement[]) => void }) {
  const [term, setTerm] = useState(""); const [status, setStatus] = useState("");
  const filtered = rows.filter((item) => (!status || item.status === status) && `${item.productDescription} ${item.productCode} ${item.sector}`.toLowerCase().includes(term.toLowerCase()));
  function exportCsv() { const header = ["Data","Setor","Código","Produto","Referência","Quantidade","Situação","Ação","Status","Observação","Custo"]; download(`contagens-${today()}.csv`, "\ufeff" + [header, ...filtered.map((x) => [x.date,x.sector,x.productCode,x.productDescription,x.reference,x.quantity,x.situation,x.action,x.status,x.notes,x.cost])].map((r) => r.map(csv).join(";")).join("\n")); }
  return <div className="panel table-panel"><div className="balance-toolbar"><div><h2>Contagens do balanço</h2><span>{filtered.length} registros encontrados</span></div><div><Button variant="outline" onClick={exportCsv}><Download size={16}/> CSV</Button><Button onClick={onNew}><Plus size={16}/> Nova contagem</Button></div></div><div className="balance-filters"><div className="inline-search"><Search size={17}/><Input value={term} onChange={(e) => setTerm(e.target.value)} placeholder="Produto, código ou setor..."/></div><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos os status</option><option>Concluído</option><option>Pendente</option><option>Conferir</option></select></div>{filtered.length ? <div className="balance-table-wrap"><table><thead><tr><th>Data</th><th>Produto</th><th>Setor</th><th>Qtd.</th><th>Situação</th><th>Status</th><th/></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{dateLabel(item.date)}</td><td><strong>{item.productDescription}</strong><small>Cód. {item.productCode || "—"}</small></td><td>{item.sector || "—"}</td><td><strong>{number(item.quantity)}</strong></td><td>{item.situation}<small>{item.action}</small></td><td><Badge variant={item.status === "Concluído" ? "default" : "secondary"}>{item.status}</Badge></td><td><button className="row-delete" onClick={() => { if (confirm("Excluir esta contagem?")) onChange(rows.filter((x) => x.id !== item.id)); }}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div> : <BalanceEmpty text="Nenhuma contagem encontrada."/>}</div>;
}

function Sectors({ rows, onNew, onChange }: { rows: Sector[]; onNew: () => void; onChange: (rows: Sector[]) => void }) { return <div className="panel table-panel"><div className="balance-toolbar"><div><h2>Setores e responsáveis</h2><span>Organize as áreas físicas da contagem.</span></div><Button onClick={onNew}><Plus size={16}/> Novo setor</Button></div><div className="sector-grid">{rows.map((item) => <article key={item.id}><div className="sector-icon"><MapPinned/></div><div><strong>{item.name}</strong><span>{item.location || "Local não informado"}</span><small>{item.owner || "Sem responsável"}</small></div><Badge variant={item.status === "Concluído" ? "default" : "secondary"}>{item.status}</Badge><button className="row-delete" onClick={() => { if (confirm("Excluir este setor?")) onChange(rows.filter((x) => x.id !== item.id)); }}><Trash2 size={16}/></button></article>)}</div></div>; }

function DailyView({ rows, productsTotal, onNew, onChange }: { rows: Daily[]; productsTotal: number; onNew: () => void; onChange: (rows: Daily[]) => void }) { const launched = rows.reduce((s,x) => s+x.launched,0); const average = rows.length ? Math.round(launched/rows.length) : 0; const forecast = average ? Math.ceil(Math.max(0,productsTotal-launched)/average) : 0; return <><div className="metric-grid"><Metric label="Dias registrados" value={number(rows.length)} hint="Jornadas de balanço"/><Metric label="Itens lançados" value={number(launched)} hint={`${number(Math.max(0,productsTotal-launched))} restantes`}/><Metric label="Média diária" value={number(average)} hint="Itens por jornada"/><Metric label="Previsão" value={forecast ? `${forecast} dias` : "—"} hint="No ritmo atual"/></div><div className="panel table-panel"><div className="balance-toolbar"><div><h2>Produtividade diária</h2><span>Resultado de cada jornada de balanço.</span></div><Button onClick={onNew}><Plus size={16}/> Adicionar dia</Button></div>{rows.length ? <div className="balance-table-wrap"><table><thead><tr><th>Data</th><th>Equipe</th><th>Contados</th><th>Lançados</th><th>Cadastros</th><th>Pendências</th><th>Conferências</th><th/></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><strong>{dateLabel(item.date)}</strong></td><td>{item.employees}</td><td>{number(item.counted)}</td><td><strong>{number(item.launched)}</strong></td><td>{item.registrations}</td><td>{item.pending}</td><td>{item.checks}</td><td><button className="row-delete" onClick={() => onChange(rows.filter((x) => x.id !== item.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div> : <BalanceEmpty text="Nenhuma jornada registrada."/>}</div></>; }

function MovementDialog({ open, onOpenChange, products, sectors, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; products: Product[]; sectors: Sector[]; onSave: (item: Movement) => Promise<boolean> }) {
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Product|null>(null); const [date,setDate]=useState(today()); const [sector,setSector]=useState(""); const [quantity,setQuantity]=useState(""); const [reference,setReference]=useState(""); const [situation,setSituation]=useState<Movement["situation"]>("Cadastrado"); const [action,setAction]=useState("Estoque atualizado"); const [status,setStatus]=useState<Movement["status"]>("Concluído"); const [notes,setNotes]=useState("");
  const results = useMemo(() => { const q=query.toLowerCase().trim(); if(q.length<2)return []; return products.filter((p)=>`${p.description} ${p.code} ${p.brand} ${p.supplier}`.toLowerCase().includes(q)).slice(0,8); },[products,query]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if(!selected||!quantity||!sector)return; const saved=await onSave({id:uid(),date,sector,productCode:selected.code,productDescription:selected.description,reference,quantity:Number(quantity),situation,action,status,notes,cost:Number(selected.cost)||0}); if(saved){onOpenChange(false);setSelected(null);setQuery("");setQuantity("");setSector("");} }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-[680px]"><DialogHeader><DialogTitle>Nova contagem física</DialogTitle></DialogHeader><form className="balance-form" onSubmit={submit}><label className="wide">Produto do catálogo<Input value={selected ? selected.description : query} onChange={(e)=>{setSelected(null);setQuery(e.target.value)}} placeholder="Digite nome, código, marca ou fornecedor..."/>{!selected&&results.length>0&&<div className="product-results">{results.map((p)=><button type="button" key={p.id} onClick={()=>{setSelected(p);setQuery("")}}><strong>{p.description}</strong><span>Cód. {p.code||"—"} · {p.supplier}</span></button>)}</div>}{selected&&<div className="selected-balance-product"><Check size={16}/><span>Código {selected.code||"—"} · NCM {selected.ncm||"—"}</span><button type="button" onClick={()=>setSelected(null)}>Trocar</button></div>}</label><label>Data<Input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><label>Setor<select required value={sector} onChange={(e)=>setSector(e.target.value)}><option value="">Selecione</option>{sectors.map((s)=><option key={s.id}>{s.name}</option>)}</select></label><label>Referência física<Input value={reference} onChange={(e)=>setReference(e.target.value)}/></label><label>Quantidade física<Input type="number" min="0.01" step="any" required value={quantity} onChange={(e)=>setQuantity(e.target.value)}/></label><label>Situação no sistema<select value={situation} onChange={(e)=>setSituation(e.target.value as Movement["situation"])}><option>Cadastrado</option><option>Não cadastrado</option><option>Dúvida</option></select></label><label>Ação realizada<select value={action} onChange={(e)=>setAction(e.target.value)}><option>Estoque atualizado</option><option>Produto cadastrado e estoque lançado</option><option>Enviado para conferência</option><option>Nenhuma</option></select></label><label>Status<select value={status} onChange={(e)=>setStatus(e.target.value as Movement["status"])}><option>Concluído</option><option>Pendente</option><option>Conferir</option></select></label><label className="wide">Observações<textarea rows={3} value={notes} onChange={(e)=>setNotes(e.target.value)}/></label><div className="balance-form-actions"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={!selected||!quantity||!sector}><Check size={16}/> Salvar contagem</Button></div></form></DialogContent></Dialog>;
}

function SectorDialog({ open,onOpenChange,onSave }: { open:boolean; onOpenChange:(open:boolean)=>void; onSave:(item:Sector)=>Promise<boolean> }) { const [name,setName]=useState(""); const [location,setLocation]=useState(""); const [owner,setOwner]=useState(""); const [status,setStatus]=useState<Sector["status"]>("Não iniciado"); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Novo setor</DialogTitle></DialogHeader><form className="balance-form" onSubmit={async(e)=>{e.preventDefault();const saved=await onSave({id:uid(),name,location,owner,start:"",end:"",status,notes:""});if(saved){onOpenChange(false);setName("");setLocation("");setOwner("");}}}><label>Nome<Input required value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Localização<Input value={location} onChange={(e)=>setLocation(e.target.value)}/></label><label className="wide">Responsável<Input value={owner} onChange={(e)=>setOwner(e.target.value)}/></label><label>Status<select value={status} onChange={(e)=>setStatus(e.target.value as Sector["status"])}><option>Não iniciado</option><option>Em andamento</option><option>Concluído</option><option>Pausado</option></select></label><div className="balance-form-actions"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit">Salvar setor</Button></div></form></DialogContent></Dialog>; }

function DailyDialog({ open,onOpenChange,onSave }: { open:boolean; onOpenChange:(open:boolean)=>void; onSave:(item:Daily)=>Promise<boolean> }) { const [form,setForm]=useState({date:today(),employees:"",counted:"",launched:"",registrations:"",pending:"",checks:"",notes:""}); const change=(key:string,value:string)=>setForm((x)=>({...x,[key]:value})); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Adicionar produtividade diária</DialogTitle></DialogHeader><form className="balance-form" onSubmit={async(e)=>{e.preventDefault();const saved=await onSave({id:uid(),date:form.date,employees:Number(form.employees)||0,counted:Number(form.counted)||0,launched:Number(form.launched)||0,registrations:Number(form.registrations)||0,pending:Number(form.pending)||0,checks:Number(form.checks)||0,notes:form.notes});if(saved){onOpenChange(false);setForm({date:today(),employees:"",counted:"",launched:"",registrations:"",pending:"",checks:"",notes:""});}}}><label>Data<Input required type="date" value={form.date} onChange={(e)=>change("date",e.target.value)}/></label><label>Funcionários<Input type="number" min="0" value={form.employees} onChange={(e)=>change("employees",e.target.value)}/></label><label>Itens contados<Input type="number" min="0" value={form.counted} onChange={(e)=>change("counted",e.target.value)}/></label><label>Itens lançados<Input type="number" min="0" value={form.launched} onChange={(e)=>change("launched",e.target.value)}/></label><label>Cadastros realizados<Input type="number" min="0" value={form.registrations} onChange={(e)=>change("registrations",e.target.value)}/></label><label>Pendências<Input type="number" min="0" value={form.pending} onChange={(e)=>change("pending",e.target.value)}/></label><label>Conferências<Input type="number" min="0" value={form.checks} onChange={(e)=>change("checks",e.target.value)}/></label><label className="wide">Observações<textarea rows={3} value={form.notes} onChange={(e)=>change("notes",e.target.value)}/></label><div className="balance-form-actions"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit">Salvar jornada</Button></div></form></DialogContent></Dialog>; }
